"""
This type stub file was generated by pyright.
"""

from typing import Generic, TypeVar

from pydantic import BaseModel

_T = TypeVar("_T")
class BaseResponse(BaseModel, Generic[_T]):
    data: _T


class ListResponse(BaseResponse[list[_T]]):
    ...


class PaginationMeta(BaseModel):
    per_page: int | None = ...
    next_cursor: int | None = ...


class PaginatedListResponse(BaseResponse[list[_T]]):
    meta: PaginationMeta


class BaseAPI(Generic[_T]):
    model_class = ...
    def __init__(self, client) -> None:
        ...
    


