"""
This type stub file was generated by pyright.
"""

from typing import Generic, List, Optional, TypeVar
from pydantic import BaseModel

T = TypeVar("T")
class BaseResponse(BaseModel, Generic[T]):
    data: T
    ...


class ListResponse(BaseResponse[List[T]]):
    ...


class PaginationMeta(BaseModel):
    per_page: Optional[int] = ...
    next_cursor: Optional[int] = ...


class PaginatedListResponse(BaseResponse[List[T]]):
    meta: PaginationMeta
    ...


class BaseAPI(Generic[T]):
    model_class = ...
    def __init__(self, client) -> None:
        ...
    


