"""
This type stub file was generated by pyright.
"""

from typing import Optional

class BallDontLieException(Exception):
    def __init__(self, message: str, status_code: Optional[int] = ..., response_data: Optional[dict] = ...) -> None:
        ...
    


class AuthenticationError(BallDontLieException):
    ...


class RateLimitError(BallDontLieException):
    ...


class ValidationError(BallDontLieException):
    ...


class NotFoundError(BallDontLieException):
    ...


class ServerError(BallDontLieException):
    ...


