"""
This type stub file was generated by pyright.
"""


class BallDontLieException(Exception):
    def __init__(self, message: str, status_code: int | None = ..., response_data: dict | None = ...) -> None:
        ...
    


class AuthenticationError(BallDontLieException):
    ...


class RateLimitError(BallDontLieException):
    ...


class ValidationError(BallDontLieException):
    ...


class NotFoundError(BallDontLieException):
    ...


class ServerError(BallDontLieException):
    ...


