"""
This type stub file was generated by pyright.
"""

from typing import List, Optional
from ..base import BaseAPI, BaseResponse, ListResponse, PaginatedListResponse
from .models import *

class NBATeamsAPI(BaseAPI[NBATeam]):
    model_class = NBATeam
    def list(self, division: Optional[str] = ..., conference: Optional[str] = ...) -> ListResponse[NBATeam]:
        ...
    
    def get(self, team_id: int) -> BaseResponse[NBATeam]:
        ...
    


class NBAPlayersAPI(BaseAPI[NBAPlayer]):
    model_class = NBAPlayer
    def list(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., team_ids: Optional[List[int]] = ..., player_ids: Optional[List[int]] = ..., search: Optional[str] = ..., first_name: Optional[str] = ..., last_name: Optional[str] = ...) -> PaginatedListResponse[NBAPlayer]:
        ...
    
    def get(self, player_id: int) -> BaseResponse[NBAPlayer]:
        ...
    
    def list_active(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., team_ids: Optional[List[int]] = ..., player_ids: Optional[List[int]] = ..., search: Optional[str] = ..., first_name: Optional[str] = ..., last_name: Optional[str] = ...) -> PaginatedListResponse[NBAPlayer]:
        ...
    


class NBAGamesAPI(BaseAPI[NBAGame]):
    model_class = NBAGame
    def list(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., dates: Optional[List[str]] = ..., team_ids: Optional[List[int]] = ..., seasons: Optional[List[int]] = ..., postseason: Optional[bool] = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ...) -> PaginatedListResponse[NBAGame]:
        ...
    
    def get(self, game_id: int) -> BaseResponse[NBAGame]:
        ...
    


class NBAStatsAPI(BaseAPI[NBAStats]):
    model_class = NBAStats
    def list(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., player_ids: Optional[List[int]] = ..., game_ids: Optional[List[int]] = ..., dates: Optional[List[str]] = ..., seasons: Optional[List[int]] = ..., postseason: Optional[bool] = ..., start_date: Optional[str] = ..., end_date: Optional[str] = ...) -> PaginatedListResponse[NBAStats]:
        ...
    


class NBASeasonAveragesAPI(BaseAPI[NBASeasonAverages]):
    model_class = NBASeasonAverages
    def get(self, season: int, player_id: int) -> ListResponse[NBASeasonAverages]:
        ...
    


class NBAStandingsAPI(BaseAPI[NBAStandings]):
    model_class = NBAStandings
    def get(self, season: int) -> ListResponse[NBAStandings]:
        ...
    


class NBABoxScoresAPI(BaseAPI[NBABoxScore]):
    model_class = NBABoxScore
    def get_live(self) -> ListResponse[NBABoxScore]:
        ...
    
    def get_by_date(self, date: str) -> ListResponse[NBABoxScore]:
        ...
    


class NBAPlayerInjuriesAPI(BaseAPI[NBAPlayerInjury]):
    model_class = NBAPlayerInjury
    def list(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., team_ids: Optional[List[int]] = ..., player_ids: Optional[List[int]] = ...) -> PaginatedListResponse[NBAPlayerInjury]:
        ...
    


class NBALeadersAPI(BaseAPI[NBALeader]):
    model_class = NBALeader
    def get(self, stat_type: str, season: int) -> ListResponse[NBALeader]:
        ...
    


class NBAOddsAPI(BaseAPI[NBAOdds]):
    model_class = NBAOdds
    def list(self, date: Optional[str] = ..., game_id: Optional[int] = ...) -> ListResponse[NBAOdds]:
        ...
    


class NBAAdvancedStatsAPI(BaseAPI[NBAAdvancedStats]):
    model_class = NBAAdvancedStats
    def list(self, cursor: Optional[int] = ..., per_page: Optional[int] = ..., player_ids: Optional[List[int]] = ..., game_ids: Optional[List[int]] = ..., dates: Optional[List[str]] = ..., seasons: Optional[List[int]] = ..., postseason: Optional[bool] = ...) -> PaginatedListResponse[NBAAdvancedStats]:
        ...
    


class NBAApi:
    def __init__(self, client) -> None:
        ...
    


